### ISSUE TITLE
Move par table and round tracker back to the stock market

### ISSUE THREAD

**Issue by Galatolol** [18xx-maker/18xx-maker#175]
Would it be possible to add an option of having par table and round tracker on the same page as the stock market (as it was before)?

**Comment by kelsin** [comment]
@Galatolol definitely. I removed them due to getting too bogged down in layout when trying to redo the markets. Now that markets are redone and I've been playing with them I think I'm going to make the following changes. Please let me know if this sounds ok:

1) Remove a lot of the market sizing option. There should be ONE option for how tall and wide a single grid item is, that defaults to community-liked options. I'll probably find out what JCL is using currently and default to that.

2) 1D markets default to width by 4*height. 1Diag markets default to width by 2*height without options to set them individually. Par charts default to 3*width by height. This is instead of being able to set each type. I don't think each type is useful, but being able to have tighter or bigger markets as a preference in general I still think is worthwhile?

3) Then in a game file, you can say if you want the par on the market. If you say so without positioning help, we just position the par chart in the bottom right of the market like we did before.  On 1D and 1Diag markets we position the par chart sideways beneath the market.

4) Finally you can also set a position for the par if you want that will offset (by your standard cell size) exactly where the par chart is positioned for cases where the chart isn't perfect.

5) More options for par charts that are laid out in ways other than just ONE column. This will include options for making different par boxes different sizes (in multiples of the default cell size etc).

Does all of that sound... worth while / good? Something we want? Any opinions wanted.

**Comment by Galatolol** [comment]
1. JCL is currently using 0.8"x1.5" (21mm x 38mm). I find them too tall (I attach the image of how it looks, nevermind the position of values. BTW in paginated, this is 6 A4 pages)

The rest sounds good! What about round tracker, it belongs on the stock market as well ;) 

[market.pdf](https://github.com/kelsin/18xx/files/4108573/market.pdf)

**Comment by kelsin** [comment]
Ok initial work on this is in master.

In order for a par or roundTrack to appear on a market two things must be set:
* In `config.json` the field `stock.display.par` and `stock.display.roundTrack` must be set to `true` (they are by default, in a browser make sure to reset config values to load the new defaults at some point).
* The game file has to define the positions on where to put them in `stock.display.par` and `stock.display.roundTracker`. Examples of this are in 1830.json.

So the game has to decide where to place them, and you have to decide to show them. The best would be all games placing them whenever possible and people using config to choose where they like it (map or market or none).

Let me know how this feels and if this solves any use cases. I didn't change the default cell size yet, but can if people want later.

**Comment by kelsin** [comment]
Example: https://www.18xx-maker.com/1830/market

Have definite work to do with market legends... don't like them, and don't know what to do about it.

There's also some work to do in case you put the par chart outside of the normal market area, I don't handle that right now.

**Comment by kelsin** [comment]
Markets can be extended down and to the right via the par table at the moment.

**Comment by Galatolol** [comment]
I have an issue with the par table. This is 1830 on master:

![par](https://user-images.githubusercontent.com/10097748/75120041-75326780-5688-11ea-9123-da49998f879b.png)

**Comment by kelsin** [comment]
I need to solve this in a better way, but go to the config page and click
the reset button on the bottom.

Chris

**Comment by Galatolol** [comment]
It works fine in new versions of 18xx-maker.
