### ISSUE TITLE
New line / line break ?

### ISSUE THREAD

**Issue by goldencow2** [18xx-maker/18xx-maker#340]
Is it possible for 18xx-maker to recognize "\n" or the like? I'm trying to make a stock market with three values per box as in the image below.
![](https://cdn.discordapp.com/attachments/609705407136661524/728491355898380368/Untitled.png)

Private, train, and phase descriptions would also stand to benefit if their text could be broken into paragraphs.

**Comment by kelsin** [comment]
What's the purpose of those values on that stock market? I try to make most things in 18xx-maker game files functional and descriptive instead of just layout oriented. I'd rather do something like make the box value be able to be an array of three values with other options for what they mean instead of just allowing newlines in the text.

It's also the case that SVG (until we get version 2 everywhere) can't do multi-line text so any element that's an SVG right now wouldn't be able to handle newlines. So I think we need to handle this on a case by case basis.

**Comment by goldencow2** [comment]
Shares have to be purchased at a higher price depending on circumstance. There's no obvious pattern, so the only method is to list the higher prices. I'll just output three stock markets and edit them together.

**Comment by kelsin** [comment]
Would still like to add features like this but don't need this issue for it.
