### ISSUE TITLE
SVG support in user-space

### ISSUE THREAD

**Issue by TheExcalabur** [18xx-maker/18xx-maker#346]
AFAICT users using the app cannot add new SVG logos to a game.  

Whilst the existing included logos can be accessed, the encapsulated application doesn't support finding external SVGs.  

A quick look at the code and I'm not sure how this can be done gracefully.  Easiest suggestion would be to check a filepath rather than the logos import if logos[logo] doesn't exist? 

```
else if logo { go find it it in the filesystem}
``` 

at line 155 of Token.jsx?  

I may be able to hack that together....

**Comment by kelsin** [comment]
This is a thing we want to plan and after upgrading everything should be possible. Will be looking at this and saving items that users upload to the OPFS. This is probably a 2.0 thing however... but going to close this for now. This won't be forgotten about since it's a major feature that I want supported either on the web OR in the app.
